api:
  replicas: 1

  image:
    repository: ghcr.io/galacticgit007/task-api
    tag: latest

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

frontend:
  replicas: 1

  image:
    repository: ghcr.io/galacticgit007/task-frontend
    tag: latest

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
