name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push API
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/galacticgit007/task-api:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/galacticgit007/task-frontend:latest

      - name: Deploy to k3s
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/task-api
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
            helm upgrade --install task-app helm/task-app
            kubectl rollout status deployment/task-api --timeout=120s
            kubectl rollout status deployment/task-frontend --timeout=120s
